config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("materials/", include("materials.urls", namespace="materials")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import contact, StudentListView, StudentCreateView, StudentDetailView, StudentUpdateView, \
    StudentDeleteView, toggle_activity

app_name = MainConfig.name

urlpatterns = [
    path("", StudentListView.as_view(), name="index"),
    path("contact/", contact, name="contact"),
    path("create/", StudentCreateView.as_view(), name='create'),
    path("view/<int:pk>", StudentDetailView.as_view(), name='student_detail'),
    path("edit/<int:pk>", StudentUpdateView.as_view(), name='update_student'),
    path("delete/<int:pk>", StudentDeleteView.as_view(), name='delete_student'),
    path("activity/<int:pk>", toggle_activity, name='toggle_activity'),
]

materials/urls.py
from django.urls import path

from materials.apps import MaterialsConfig
from materials.views import MaterialCreateView, MaterialListView, MateriaDetailView, MaterialUpdateView, MateriaDelete

app_name = MaterialsConfig.name

urlpatterns = [
    path("create/", MaterialCreateView.as_view(), name="create"),
    path("", MaterialListView.as_view(), name="list",),
    path("view/<int:pk>", MateriaDetailView.as_view(), name="view"),
    path("edit/<int:pk>", MaterialUpdateView.as_view(), name="edit"),
    path("delete/<int:pk>", MateriaDelete.as_view(), name="delete"),
]

materials/models.py
from django.db import models


class Materials(models.Model):
    title = models.CharField(max_length=150, verbose_name='Название')
    body = models.TextField(verbose_name='Содержимое')

    views_count = models.IntegerField(default=0, verbose_name='Просмотры')
    is_publish = models.BooleanField(default=True, verbose_name='Опубликовано')
    slug = models.CharField(max_length=150, verbose_name='slug', null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Материал'
        verbose_name_plural = 'Материалы'

materials/views.py
from django.urls import reverse_lazy, reverse
from django.utils.text import slugify
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from materials.models import Materials


class MaterialCreateView(CreateView):
    model = Materials
    fields = ('title', 'body',)
    success_url = reverse_lazy('materials:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)


class MaterialUpdateView(UpdateView):
    model = Materials
    fields = ('title', 'body',)
    # success_url = reverse_lazy('materials:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('materials:view', args=[self.kwargs.get('pk')])


class MaterialListView(ListView):
    model = Materials

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_publish=True)
        return queryset


class MateriaDetailView(DetailView):
    model = Materials

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class MateriaDelete(DeleteView):
    model = Materials
    success_url = reverse_lazy('materials:list')

materials/templates/materials/materials_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить "{{ object.title }}"</p>
                            <button type="submit" class="btn btn-success">Подтвердить</button>
                            <a href="{% url 'materials:list' %}" class="btn btn-warning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

materials/templates/materials/materials_detail.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Материал {{ object.title }} ({{ object.slug }})
                        </h3>
                    </div>
                    <div class="card-body">
                        <p>
                            {{ object.body }}
                        </p>
                    </div>
                    <div class="card-footer">
                        Просмотры - {{ object.views_count }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

materials/templates/materials/materials_form.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">
                                {% if object %}
                                    Сохранить
                                {% else %}
                                    Создать
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

materials/templates/materials/materials_list.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12 mb-5">
        <a class="btn btn-outline-primary" href="{% url 'materials:create' %}">Добавить материал</a>
    </div>
    {% for object in object_list %}
        <div class="col">
            <div class="card shadow-sm">
                <div class="card-body">
                    <p class="card-text">
                        {{ object|title }}
                    </p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="{% url 'materials:view' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">View</a>
                            <a href="{% url 'materials:edit' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Edit</a>
                            <a href="{% url 'materials:delete' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Delete</a>
                        </div>
                        <small class="text-body-secondary">9 mins</small>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}